# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71c65aeb9ff11d0c5c08235cbc3b2fe21daffcd2adf637baa59d73681d4d04f0a06bbd7768702a0865372c4f2dc08b636e9d647f48ba5337125e237a7a31b7c9

test:
  secret_key_base: 904d3e8347b145fc7d7041de441be2c6a770005dfa04840eeb1bc0be8bfd06f4bb9b9309b9f9c61e2b3d967b5d9bb0de15b18b85a0384174d363b961b413cdb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
